---
version: "3"
services:
 devopsdb:
   container_name: devopsdb
   image: saikrishnakopparapu1/project:DBimage
   ports:
     - "3306:3306"

 application:
   image: saikrishnakopparapu1/project:Appimage
   container_name: containerapp
   ports:
     - "1234:8080"
   depends_on:
     - "devopsdb"
