---
services:
  appservice:
    image: appimage
    ports:
      - "1111:8080"
    depends_on:
      - devopsdb

  devopsdb:
    image: dbimage
    ports:
      - "3306:3306"
    volumes:
      - userdata:/var/lib/mysql
    deploy:
      resources:
        reservations:
          cpus: "0.5"
          memory: 500M
        limits:
          cpus: "1.0"
          memory: 1000M

volumes:
  userdata:
